### ISSUE TITLE
Better example of rigidity

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/modern-scientific-authoring#19]
From @sprossiter:

```
You could do with a better example of why WYSIWYG editors are rigid, since changing the page size is
something I imagine many Word-preferring-readers will think of as "Yeah but why would I ever be doing
that?". Maybe something to do with anchoring images to paragraphs and what happens when you
move/delete that paragraph? (I'm sure there are better examples.)
```

**Comment by emilydolson** [comment]
How about re-submitting something to a different journal with different rules on how headings and such should be formatted?

**Comment by gvwilson** [comment]
I like this one - thanks!

**Comment by sprossiter** [comment]
@emilydolson @gvwilson That is a cleaner example Emily but doesn't my comment in issue #15 apply; i.e., this _isn't_ a major problem in Word if you're using styles properly (though it does mean you have to edit the 'source file' rather than some separated styling info; you'd still often be doing that in LaTeX anyway, say to use a required set of packages _which might actually require you to edit a whole set of markup as well_, say to use the amsmaths package for an AMS submission). Am I missing something here?

**Comment by sprossiter** [comment]
Issue #14 relates to this discussion as well...

**Comment by emilydolson** [comment]
Wow, I had no idea that anything like that existed in Word! That may indeed invalidate this example.
