### ISSUE TITLE
Opinions about org-mode?

### ISSUE THREAD

**Issue by cpaulik** [swcarpentry/modern-scientific-authoring#29]
Reading through a lot of the discussions on the `swcarpentry` pages I've not really encountered [org-mode](http://orgmode.org/). Is that for a specific reason or is it just not known well enough? Because in my opinion it has pretty much all the features that one needs for modern-scientific authoring and/or reproducible research. See for example [this paper](https://www.jstatsoft.org/article/view/v046i03) about org mode for reproducible research.
- Text based
- Good support for bibliography management through [org-ref](https://github.com/jkitchin/org-ref)
- Math support using LateX syntax
- Export to LateX
- Inline code in multiple languages that can be executed and the results used in the text. 
- Code can be "tangled" to other files on disk.
- no syntax fragmentation like markdown
  ....

I guess the main thing holding it back is that it depends on emacs to be really useful.

**Comment by wking** [comment]
On Fri, Feb 12, 2016 at 02:45:30PM -0800, Christoph Paulik wrote:

> Reading through a lot of the discussions on the `swcarpentry` pages
> I've not really encountered [org-mode](http://orgmode.org/).

I occasionally use Org mode.

> See for example [this
> paper](https://www.jstatsoft.org/article/view/v046i03) about org
> mode for reproducible research.

Gotta love a paper where the package source is posted as a supplement
:).

> - no syntax fragmentation like markdown

But also a single provider, unless some of the projects in [1](http://orgmode.org/worg/org-tools/index.html) are
more robust/comprehensive than my first impressions suggest.  On the
other hand, Pandoc supports “Org mode”, although I don't know if that
covers _all_ of Org mode [2](http://orgmode.org/manual/index.html).

> I guess the main thing holding it back is that it depends on emacs
> to be really useful.

That's my guess too.  And I live in Emacs, but it's a hard sell for
occasional users.

**Comment by naupaka** [comment]
I _love_ org-mode. I think it is one of the best solutions to all these challenges, plus amazing table support, project management through gantt charts, task tracking, the whole 9 yards. GitHub renders it as well, so you can have a README.org if you like. I use it for everything I can. I know @karawoo is a big fan too.

The primary downside is, as was already mentioned, that you need to have a fair level of comfort with emacs in general and org-mode specifically to get much use out of it, and I would wager it is a non-starter for any but chronic editor enthusiasts among us to dive into such deep waters when there are many other things competing for precious time. It's kind of like the challenge of selling people on Julia -- it's a great language, but a hard sell if you have someone who already uses R and python and is getting by just fine thank you very much. Plus things like Jupyter or Rmarkdown are so much closer to working out of the box than emacs, which can take some serious configuring before it starts to work as one might like.

I think one of the major reasons emacs it isn't mentioned much is the same reason vim isn't mentioned much. The focus of SWC as I understand it is on the concepts and not the tools, and having a complex and powerful tool can be nice, but it makes it hard to teach the concepts since it adds many additional layers of complexity.

**Comment by karawoo** [comment]
+1 to everything @naupaka said

**Comment by plantarum** [comment]
As a big fan of org-mode, I have to say it suffers from _de facto_ lock-in that will limit it to a very small minority of academic researchers. While there is nothing to stop a developer from building their own org-mode editor aimed at the WYSIWYG GUI market, that's going to be a very hard sell. 

Essentially you'd be asking your users to walk away from their existing tool set and learn a whole new approach. The payoff for this effort is that they would then be able to collaborate more easily with that weird guy who's computer looks like a DOS prompt and is always talking about LaTeX. Not bloody likely.

Like it or not, the tools matter. Most naive computer users don't distinguish between the tools and the concepts. I have been using Emacs and org-mode for years, but until very recently I use Emacs only for first drafts. As soon as I need to collaborate, I export the document to docx and work from LibreOffice from that point forwards.

This is starting to change, because of RMarkdown. However, the real key to success here is RStudio. Now that I have collaborators using RStudio, I can send them .Rmd files and they can actually work with them. 

If org-mode is ever going to gain traction outside of Emacs it will have to adopt Markdown formatting[1]. It probably wouldn't be that hard to do, as the syntax used by both is quite similar. But this will only happen if the Emacs die-hards developing org-mode see an upside to sharing their work with the wider world, and that upside is enough to change their established practices.

A more likely scenario for cross-platform collaboration with Emacs is polymode. If Vitali can get the bugs ironed out, that will allow painless sharing between Emacs, RStudio, and any other editor that supports RMarkdown.

[1] it's also possible someone could implement org-mode outside of Emacs. But it's hard to imagine a developer exists that both a) loves org-mode enough to build an editor for it, and b) would want to use org-mode in anything other than Emacs in the first place.

**Comment by cpaulik** [comment]
Thanks for the replies. 

I agree with most that was said. 

It really is a pity that a tool that could be one solution can not be adapted because of a lack of time or willingness to try something new. But I fully realize that that is how it is and that learning org-mode in emacs is not the easiest thing. But I have to say that I've struggled more with MS word than with emacs. 

@plantarum I don't think that adapting markdown formatting would bring any real benefits since the formatting is so similar that they can be easily converted. Or edited with any text editor (there are already modes for that for vim, atom and I think sublime text). The bigger problem are the advanced features like running and tangling code in different languages.

Are there any plans to expand RMarkdown to more languages? Personally I use  Python quite a bit and am not satisfied with an R only solution. IPython/Jupyter do support more kernels but the format is text but not really readable without a renderer.

**Comment by plantarum** [comment]
@cpaulik it's true you **can** edit org mode files in any editor, but if that editor doesn't support any of the advanced features of org-mode, why would you want to? What do you gain over using the more widespread markdown? Being equally easy is not good enough, if you are requiring someone to move away from something they know. It has to be clearly better. And it's true that you can easily convert back and forth, but the added hassle would eat up any benefit you hoped to gain from using version control to track and merge changes.

The benefit of org mode using markdown format would be that it would then become truly editor-agnostic - I could edit in Emacs, you could edit in RStudio, and we can both take full advantage of knitr to compile our document. As it is, we can both edit the code in any editor, but only those of us using Emacs can compile the document. And for those of us not using Emacs, there is no advantage over markdown in that case.

If we were all using plain text formats, and we were debating which one is best, then it makes sense to argue about org vs md vs rst. But realistically, at least in my field, the debate is between Word and anything else. We can make a much more persuasive argument if the 'anything else' category isn't a slowly diverging collection of sort-of compatible formats, but is a single format with a variety of tools available on all platforms.

As far as expanding RMarkdown, Emacs + polymode can handle code chunks in any language, in theory. I'm not sure how the 'knitting' step is handled, if at all, though, or if it's done in a way that is not locked to Emacs.

**Comment by gvwilson** [comment]
cf. 
http://software-carpentry.org/blog/2016/02/collaboration-counterpoint.html

**Comment by naupaka** [comment]
@cpaulik @plantarum You can use knitr to knit markdown documents that include a bunch of languages, not just R. See the list and examples [here](http://yihui.name/knitr/demo/engines/).

**Comment by cpaulik** [comment]
@plantarum @naupaka I do not really see the difference between installing Knitr or emacs so these two, lets call them build systems, are equal in my opinion. 

I share the opinion that it would be best if people in the "text-based-workflow" camp could agree on a standard to have a chance of competing with word.

**Comment by naupaka** [comment]
My sense of the argument for Rmarkdown over org-mode is that Rmarkdown/knitr works really well out of the box with RStudio.  Setup is prohibitive with emacs.

**Comment by cpaulik** [comment]
@naupaka Setup with emacs can be taken care of. If there is interest we could bundle emacs with a well working org-mode configuration for scientific writing. Or provide a emacs configuration/starter kit targeted at researchers. 

The [spacemacs](https://github.com/syl20bnr/spacemacs) org layer together with my [research config layer](https://github.com/cpaulik/dotfiles/blob/master/.spacemacs-config/config-layers/research-config/packages.el) could be a starting point. 

After that getting a running org mode system is as easy as 
- installing emacs
- cloning a github repo into `.emacs.d`
- Learning the syntax and a few export keybindings/menu options.

The first two steps might even be bundled into one installer without major effort.

**Comment by gvwilson** [comment]
I don't think we're going to introduce Emacs to our learners any time soon... close this?

**Comment by naupaka** [comment]
Sounds good to me. Might not be inappropriate to include org-mode in some list somewhere of 'other options' or something. But I agree it's not worth trying to teach in a workshop.

**Comment by cpaulik** [comment]
I still don't think that an emacs starter kit for researchers would be harder to learn than e.g. RMarkdown and knitr but maybe that is only me. I would appreciate it if org-mode could be mentioned in the list of other options. If time permits I might start with the before-mentioned starter kit / explanation so that more people loose their "fear" of emacs :smile:
